/**
 * @file Action creators for minion-related operations
 * @module minionActions
 */

import { MINION_ACTIONS } from '../reducers/minionsReducer';

/**
 * Buy a quantity of a specific minion type
 * @param {string} minionId - ID of the minion to buy
 * @param {number} [amount=1] - Number of minions to buy
 * @returns {Object} Action object
 */
export const buyMinion = (minionId, amount = 1) => ({
  type: MINION_ACTIONS.BUY_MINION,
  payload: {
    minionId,
    amount
  }
});

/**
 * Upgrade a specific minion type to increase production
 * @param {string} minionId - ID of the minion to upgrade
 * @returns {Object} Action object
 */
export const upgradeMinion = (minionId) => ({
  type: MINION_ACTIONS.UPGRADE_MINION,
  payload: {
    minionId
  }
});

/**
 * Collect resources generated by minions
 * @param {number} [timestamp=Date.now()] - Collection timestamp
 * @returns {Object} Action object
 */
export const collectResources = (timestamp = Date.now()) => ({
  type: MINION_ACTIONS.COLLECT_RESOURCES,
  payload: {
    timestamp
  }
});

/**
 * Unlock a new minion type
 * @param {string} minionId - ID of the minion to unlock
 * @returns {Object} Action object 
 */
export const unlockMinionType = (minionId) => ({
  type: MINION_ACTIONS.UNLOCK_MINION_TYPE,
  payload: {
    minionId
  }
});

/**
 * Reset all minions to their initial state
 * @returns {Object} Action object
 */
export const resetMinions = () => ({
  type: MINION_ACTIONS.RESET_MINIONS
});
