// Consolidate all action types in one place
export const ACTION_TYPES = {
  // Game initialization
  INITIALIZE_GAME_DATA: 'INITIALIZE_GAME_DATA',
  
  // Notifications
  SHOW_NOTIFICATION: 'SHOW_NOTIFICATION',
  CLEAR_NOTIFICATION: 'CLEAR_NOTIFICATION',
  
  // Player
  UPDATE_PLAYER: 'UPDATE_PLAYER',
  GAIN_EXPERIENCE: 'GAIN_EXPERIENCE',
  LEVEL_UP: 'LEVEL_UP',
  LEARN_SKILL: 'LEARN_SKILL',
  EQUIP_ITEM: 'EQUIP_ITEM',
  UNEQUIP_ITEM: 'UNEQUIP_ITEM',
  ADD_ITEM_TO_INVENTORY: 'ADD_ITEM_TO_INVENTORY',
  REMOVE_ITEM_FROM_INVENTORY: 'REMOVE_ITEM_FROM_INVENTORY',
  
  // Essence
  GAIN_ESSENCE: 'GAIN_ESSENCE',
  SPEND_ESSENCE: 'SPEND_ESSENCE',
  COLLECT_ESSENCE: 'COLLECT_ESSENCE',
  UPGRADE_ESSENCE_RATE: 'UPGRADE_ESSENCE_RATE',
  
  // Time
  ADVANCE_TIME: 'ADVANCE_TIME',
  
  // Add other action types as needed
};