// Consolidate all action types in one place
export const ACTION_TYPES = {
  // Player actions
  UPDATE_PLAYER: 'UPDATE_PLAYER',
  COPY_TRAIT: 'COPY_TRAIT',
  LEARN_SKILL: 'LEARN_SKILL',
  EQUIP_TRAIT: 'EQUIP_TRAIT',
  UNEQUIP_TRAIT: 'UNEQUIP_TRAIT',
  UPGRADE_TRAIT_SLOTS: 'UPGRADE_TRAIT_SLOTS',
  ADD_PERMANENT_TRAIT: 'ADD_PERMANENT_TRAIT',
  DISCOVER_NPC: 'DISCOVER_NPC',
  
  // Essence actions
  GAIN_ESSENCE: 'GAIN_ESSENCE',
  SPEND_ESSENCE: 'SPEND_ESSENCE',
  
  // NPC actions
  UPDATE_NPC_RELATIONSHIP: 'UPDATE_NPC_RELATIONSHIP',
  MEET_NPC: 'MEET_NPC',
  UPDATE_DIALOGUE_STATE: 'UPDATE_DIALOGUE_STATE',
  UPDATE_DIALOGUE_HISTORY: 'UPDATE_DIALOGUE_HISTORY',
  
  // Quest actions
  START_QUEST: 'START_QUEST',
  UPDATE_QUEST_PROGRESS: 'UPDATE_QUEST_PROGRESS',
  COMPLETE_QUEST: 'COMPLETE_QUEST',
  ABANDON_QUEST: 'ABANDON_QUEST',
  
  // Inventory actions
  ADD_ITEM: 'ADD_ITEM',
  REMOVE_ITEM: 'REMOVE_ITEM',
  USE_ITEM: 'USE_ITEM',
  EQUIP_ITEM: 'EQUIP_ITEM',
  UNEQUIP_ITEM: 'UNEQUIP_ITEM',
  
  // Game state
  INITIALIZE_GAME_DATA: 'INITIALIZE_GAME_DATA',
  ADVANCE_TIME: 'ADVANCE_TIME',
  
  // UI actions
  SHOW_NOTIFICATION: 'SHOW_NOTIFICATION',
  CLEAR_NOTIFICATION: 'CLEAR_NOTIFICATION'
};