

















































});  payload: { id }  type: ACTION_TYPES.REMOVE_CHARACTER,export const removeCharacter = (id) => ({ */ * @returns {Object} The formatted action object * @param {string} id - Character ID to remove *  * @description Action creator for removing a character from the roster * @function removeCharacter/**});  payload: { id, updates }  type: ACTION_TYPES.UPDATE_CHARACTER,export const updateCharacter = (id, updates) => ({ */ * @returns {Object} The formatted action object * @param {Object} updates - Properties to update * @param {string} id - Character ID *  * @description Action creator for updating an existing character's data * @function updateCharacter/**});  payload: { character }  type: ACTION_TYPES.ADD_CHARACTER,export const addCharacter = (character) => ({ */ * @returns {Object} The formatted action object * @param {Object} character - Character data object *  * @description Action creator for adding a character to the player's roster * @function addCharacter/**});  payload: { tab }  type: ACTION_TYPES.SET_CHARACTER_TAB,export const setCharacterTab = (tab) => ({ */ * @returns {Object} The formatted action object * @param {string} tab - The tab to activate *  * @description Action creator for setting the active tab in character management UI * @function setCharacterTab/**import { ACTION_TYPES } from './actionTypes';