/**
 * @fileoverview Actions related to minion management in the incremental RPG.
 * This module contains action types, action creators, and thunk actions
 * for all minion-related operations.
 */

// Action Types
/**
 * Action types for minion-related operations
 * @readonly
 * @enum {string}
 */
export const MINION_ACTION_TYPES = {
  /** Add a new minion to the player's collection */
  HIRE_MINION: 'minions/hireminion',
  /** Remove a minion from the player's collection */
  DISMISS_MINION: 'minions/dismissminion',
  /** Upgrade a minion's attributes */
  UPGRADE_MINION: 'minions/upgrademinion',
  /** Assign a minion to a specific task */
  ASSIGN_MINION: 'minions/assignminion',
  /** Unassign a minion from its current task */
  UNASSIGN_MINION: 'minions/unassignminion',
  /** Collect resources generated by minions */
  COLLECT_MINION_RESOURCES: 'minions/collectresources',
  /** Level up a minion */
  LEVEL_UP_MINION: 'minions/levelup',
  /** Set the minion collection (used for loading saved games) */
  SET_MINIONS: 'minions/setminions',
  /** Update a minion's status */
  UPDATE_MINION_STATUS: 'minions/updatestatus',
  /** Gain experience points for a minion */
  GAIN_MINION_EXPERIENCE: 'minions/gainExperience' // Add missing action type
};

// Define interfaces for action payloads
interface MinionData {
  id?: string;
  type: string;
  name: string;
  cost: number;
  stats: Record<string, number>;
  [key: string]: any;
}

interface MinionIdPayload {
  minionId: string;
}

interface MinionUpgradePayload extends MinionIdPayload {
  upgrades: Record<string, any>;
  cost: number;
}

interface MinionAssignPayload {
  minionId: string;
  taskId: string;
}

interface MinionStatusPayload {
  minionId: string;
  status: Record<string, any>;
}

interface MinionLevelUpPayload {
  minionId: string;
  cost: number;
}

// Define Thunk return type for TypeScript
type ThunkAction<R = any> = (
  dispatch: (action: any) => any, 
  getState: () => any
) => R;

// Action Creators

/**
 * Hire a new minion and add it to the player's collection
 * @param {MinionData} minionData - The minion's initial data
 * @returns {Object} The action object
 */
export const hireMinion = (minionData: MinionData) => ({
  type: MINION_ACTION_TYPES.HIRE_MINION,
  payload: minionData
});

/**
 * Dismiss a minion from the player's collection
 * @param {string} minionId - The ID of the minion to dismiss
 * @returns {Object} The action object
 */
export const dismissMinion = (minionId: string) => ({
  type: MINION_ACTION_TYPES.DISMISS_MINION,
  payload: { minionId }
});

/**
 * Upgrade a minion's attributes
 * @param {string} minionId - The ID of the minion to upgrade
 * @param {Record<string, any>} upgrades - The upgrades to apply
 * @param {number} cost - The cost of the upgrade
 * @returns {Object} The action object
 */
export const upgradeMinion = (
  minionId: string, 
  upgrades: Record<string, any>, 
  cost: number
) => ({
  type: MINION_ACTION_TYPES.UPGRADE_MINION,
  payload: { minionId, upgrades, cost }
});

/**
 * Assign a minion to a specific task
 * @param {string} minionId - The ID of the minion to assign
 * @param {string} taskId - The ID of the task to assign the minion to
 * @returns {Object} The action object
 */
export const assignMinion = (minionId: string, taskId: string) => ({
  type: MINION_ACTION_TYPES.ASSIGN_MINION,
  payload: { minionId, taskId }
});

/**
 * Unassign a minion from its current task
 * @param {string} minionId - The ID of the minion to unassign
 * @returns {Object} The action object
 */
export const unassignMinion = (minionId: string) => ({
  type: MINION_ACTION_TYPES.UNASSIGN_MINION,
  payload: { minionId }
});

/**
 * Collect resources generated by minions
 * @returns {Object} The action object
 */
export const collectMinionResources = () => ({
  type: MINION_ACTION_TYPES.COLLECT_MINION_RESOURCES
});

/**
 * Level up a minion
 * @param {string} minionId - The ID of the minion to level up
 * @param {number} cost - The cost of leveling up
 * @returns {Object} The action object
 */
export const levelUpMinion = (minionId: string, cost: number) => ({
  type: MINION_ACTION_TYPES.LEVEL_UP_MINION,
  payload: { minionId, cost }
});

/**
 * Set the entire minion collection (used when loading saved games)
 * @param {Array<MinionData>} minions - The collection of minions to set
 * @returns {Object} The action object
 */
export const setMinions = (minions: MinionData[]) => ({
  type: MINION_ACTION_TYPES.SET_MINIONS,
  payload: minions
});

/**
 * Update a minion's status
 * @param {string} minionId - The ID of the minion to update
 * @param {Record<string, any>} status - The new status properties
 * @returns {Object} The action object
 */
export const updateMinionStatus = (minionId: string, status: Record<string, any>) => ({
  type: MINION_ACTION_TYPES.UPDATE_MINION_STATUS,
  payload: { minionId, status }
});

/**
 * Award experience points to a minion
 * @param {string} minionId - The ID of the minion to award experience to
 * @param {number} amount - The amount of experience points to award
 * @returns {Object} The action object
 */
export const gainMinionExperience = (minionId: string, amount: number) => ({
  type: MINION_ACTION_TYPES.GAIN_MINION_EXPERIENCE,
  payload: { minionId, amount }
});

// Thunk Actions

/**
 * Hire a minion if the player has enough resources
 * @param {MinionData} minionData - The minion to hire
 * @returns {ThunkAction<boolean>} Thunk function
 */
export const hireMinionIfAffordable = (minionData: MinionData): ThunkAction<boolean> => (dispatch, getState) => {
  const { resources } = getState();
  
  if (resources.gold >= minionData.cost) {
    dispatch(hireMinion(minionData));
    dispatch({
      type: 'resources/spend',
      payload: { gold: minionData.cost }
    });
    return true;
  }
  
  return false;
};

/**
 * Upgrade a minion if the player has enough resources
 * @param {string} minionId - The ID of the minion to upgrade
 * @param {Record<string, any>} upgrades - The upgrades to apply
 * @param {number} cost - The cost of the upgrade
 * @returns {ThunkAction<boolean>} Thunk function
 */
export const upgradeMinionIfAffordable = (
  minionId: string, 
  upgrades: Record<string, any>, 
  cost: number
): ThunkAction<boolean> => (dispatch, getState) => {
  const { resources } = getState();
  
  if (resources.gold >= cost) {
    dispatch(upgradeMinion(minionId, upgrades, cost));
    dispatch({
      type: 'resources/spend',
      payload: { gold: cost }
    });
    return true;
  }
  
  return false;
};

/**
 * Level up a minion if the player has enough resources
 * @param {string} minionId - The ID of the minion to level up
 * @param {number} cost - The cost of leveling up
 * @returns {ThunkAction<boolean>} Thunk function
 */
export const levelUpMinionIfAffordable = (
  minionId: string, 
  cost: number
): ThunkAction<boolean> => (dispatch, getState) => {
  const { resources } = getState();
  
  if (resources.gold >= cost) {
    dispatch(levelUpMinion(minionId, cost));
    dispatch({
      type: 'resources/spend',
      payload: { gold: cost }
    });
    return true;
  }
  
  return false;
};

/**
 * Collect resources from all minions and add to player's inventory
 * This is typically called on a timer or when the player clicks a "collect" button
 * @returns {ThunkAction<Record<string, number>>} Thunk function
 */
export const harvestMinionResources = (): ThunkAction<Record<string, number>> => (dispatch, getState) => {
  interface ResourceProductions {
    gold?: number;
    wood?: number;
    stone?: number;
    food?: number;
    iron?: number;
    [key: string]: number | undefined;
  }

  interface Minion {
    id: string;
    assigned: boolean;
    productionRate?: ResourceProductions;
    [key: string]: any;
  }

  const { minions } = getState();
  let totalResources: ResourceProductions = { gold: 0, wood: 0, stone: 0, food: 0, iron: 0 };
  
  // Calculate resources generated by all assigned minions
  if (Array.isArray(minions)) {
    minions.forEach((minion: Minion) => {
      if (minion.assigned && minion.productionRate) {
        Object.keys(minion.productionRate).forEach(resource => {
          if (totalResources[resource] !== undefined && minion.productionRate?.[resource] !== undefined) {
            totalResources[resource] = (totalResources[resource] || 0) + (minion.productionRate[resource] || 0);
          }
        });
      }
    });
  }
  
  // Add resources to inventory
  if (Object.values(totalResources).some(val => (val || 0) > 0)) {
    dispatch({
      type: 'resources/add',
      payload: totalResources
    });
    dispatch(collectMinionResources());
  }
  
  return totalResources as Record<string, number>;
};
