/**
 * @fileoverview Actions related to minion management in the incremental RPG.
 * This module contains action types, action creators, and thunk actions
 * for all minion-related operations.
 */

// Action Types
/**
 * Action types for minion-related operations
 * @readonly
 * @enum {string}
 */
export const MINION_ACTION_TYPES = {
  /** Add a new minion to the player's collection */
  HIRE_MINION: 'minions/hireminion',
  /** Remove a minion from the player's collection */
  DISMISS_MINION: 'minions/dismissminion',
  /** Upgrade a minion's attributes */
  UPGRADE_MINION: 'minions/upgrademinion',
  /** Assign a minion to a specific task */
  ASSIGN_MINION: 'minions/assignminion',
  /** Unassign a minion from its current task */
  UNASSIGN_MINION: 'minions/unassignminion',
  /** Collect resources generated by minions */
  COLLECT_MINION_RESOURCES: 'minions/collectresources',
  /** Level up a minion */
  LEVEL_UP_MINION: 'minions/levelup',
  /** Set the minion collection (used for loading saved games) */
  SET_MINIONS: 'minions/setminions',
  /** Update a minion's status */
  UPDATE_MINION_STATUS: 'minions/updatestatus',
};

// Action Creators

/**
 * Hire a new minion and add it to the player's collection
 * @param {Object} minionData - The minion's initial data
 * @param {string} minionData.type - The type of minion
 * @param {string} minionData.name - The name of the minion
 * @param {number} minionData.cost - The cost to hire this minion
 * @param {Object} minionData.stats - The minion's starting stats
 * @returns {Object} The action object
 */
export const hireMinion = (minionData) => ({
  type: MINION_ACTION_TYPES.HIRE_MINION,
  payload: minionData
});

/**
 * Dismiss a minion from the player's collection
 * @param {string} minionId - The ID of the minion to dismiss
 * @returns {Object} The action object
 */
export const dismissMinion = (minionId) => ({
  type: MINION_ACTION_TYPES.DISMISS_MINION,
  payload: { minionId }
});

/**
 * Upgrade a minion's attributes
 * @param {string} minionId - The ID of the minion to upgrade
 * @param {Object} upgrades - The upgrades to apply
 * @param {number} cost - The cost of the upgrade
 * @returns {Object} The action object
 */
export const upgradeMinion = (minionId, upgrades, cost) => ({
  type: MINION_ACTION_TYPES.UPGRADE_MINION,
  payload: { minionId, upgrades, cost }
});

/**
 * Assign a minion to a specific task
 * @param {string} minionId - The ID of the minion to assign
 * @param {string} taskId - The ID of the task to assign the minion to
 * @returns {Object} The action object
 */
export const assignMinion = (minionId, taskId) => ({
  type: MINION_ACTION_TYPES.ASSIGN_MINION,
  payload: { minionId, taskId }
});

/**
 * Unassign a minion from its current task
 * @param {string} minionId - The ID of the minion to unassign
 * @returns {Object} The action object
 */
export const unassignMinion = (minionId) => ({
  type: MINION_ACTION_TYPES.UNASSIGN_MINION,
  payload: { minionId }
});

/**
 * Collect resources generated by minions
 * @returns {Object} The action object
 */
export const collectMinionResources = () => ({
  type: MINION_ACTION_TYPES.COLLECT_MINION_RESOURCES
});

/**
 * Level up a minion
 * @param {string} minionId - The ID of the minion to level up
 * @param {number} cost - The cost of leveling up
 * @returns {Object} The action object
 */
export const levelUpMinion = (minionId, cost) => ({
  type: MINION_ACTION_TYPES.LEVEL_UP_MINION,
  payload: { minionId, cost }
});

/**
 * Set the entire minion collection (used when loading saved games)
 * @param {Array<Object>} minions - The collection of minions to set
 * @returns {Object} The action object
 */
export const setMinions = (minions) => ({
  type: MINION_ACTION_TYPES.SET_MINIONS,
  payload: minions
});

/**
 * Update a minion's status
 * @param {string} minionId - The ID of the minion to update
 * @param {Object} status - The new status properties
 * @returns {Object} The action object
 */
export const updateMinionStatus = (minionId, status) => ({
  type: MINION_ACTION_TYPES.UPDATE_MINION_STATUS,
  payload: { minionId, status }
});

// Thunk Actions

/**
 * Hire a minion if the player has enough resources
 * @param {Object} minionData - The minion to hire
 * @returns {Function} Thunk function
 */
export const hireMinionIfAffordable = (minionData) => (dispatch, getState) => {
  const { resources } = getState();
  
  if (resources.gold >= minionData.cost) {
    dispatch(hireMinion(minionData));
    dispatch({
      type: 'resources/spend',
      payload: { gold: minionData.cost }
    });
    return true;
  }
  
  return false;
};

/**
 * Upgrade a minion if the player has enough resources
 * @param {string} minionId - The ID of the minion to upgrade
 * @param {Object} upgrades - The upgrades to apply
 * @param {number} cost - The cost of the upgrade
 * @returns {Function} Thunk function
 */
export const upgradeMinionIfAffordable = (minionId, upgrades, cost) => (dispatch, getState) => {
  const { resources } = getState();
  
  if (resources.gold >= cost) {
    dispatch(upgradeMinion(minionId, upgrades, cost));
    dispatch({
      type: 'resources/spend',
      payload: { gold: cost }
    });
    return true;
  }
  
  return false;
};

/**
 * Level up a minion if the player has enough resources
 * @param {string} minionId - The ID of the minion to level up
 * @param {number} cost - The cost of leveling up
 * @returns {Function} Thunk function
 */
export const levelUpMinionIfAffordable = (minionId, cost) => (dispatch, getState) => {
  const { resources } = getState();
  
  if (resources.gold >= cost) {
    dispatch(levelUpMinion(minionId, cost));
    dispatch({
      type: 'resources/spend',
      payload: { gold: cost }
    });
    return true;
  }
  
  return false;
};

/**
 * Collect resources from all minions and add to player's inventory
 * This is typically called on a timer or when the player clicks a "collect" button
 * @returns {Function} Thunk function
 */
export const harvestMinionResources = () => (dispatch, getState) => {
  const { minions } = getState();
  let totalResources = { gold: 0, wood: 0, stone: 0, food: 0, iron: 0 };
  
  // Calculate resources generated by all assigned minions
  minions.forEach(minion => {
    if (minion.assigned && minion.productionRate) {
      Object.keys(minion.productionRate).forEach(resource => {
        if (totalResources[resource] !== undefined) {
          totalResources[resource] += minion.productionRate[resource];
        }
      });
    }
  });
  
  // Add resources to inventory
  if (Object.values(totalResources).some(val => val > 0)) {
    dispatch({
      type: 'resources/add',
      payload: totalResources
    });
    dispatch(collectMinionResources());
  }
  
  return totalResources;
};
